### ISSUE TITLE
Issue with website

### ISSUE THREAD

**Issue by derekd32** [dante0527/dante.fun#1]
_Hi, I was just wondering if you could make this website actually look good?_
That would be nice...
Let me know if there's anything I could do to help.... **looks like you could use it.**

### Thanks.

**Comment by dante0527** [comment]
Hello {client name},

We are glad to hear your suggestion!
Unfortunately, {company name} has fired 50% of our engineers and has decided to use all of our extra money from the budget to purchase a super-yacht for trafficking illegal granola through the Suez canal.

Depending on how the next few months go, we may consider implementing your suggestion. If not, we hope you have a great time aging.

Thank you for reaching out!
